# Generated by Django 5.1.4 on 2024-12-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='imagetwo',
            field=models.ImageField(blank=True, null=True, upload_to='tour-imagetwo'),
        ),
    ]
